import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";

import { api } from "~/utils/api";
import About from "./About";
import Cart from "./Cart";
import Checkout from "./Checkout";
import Homepage from "./Homepage";
import Portfolio from "./Portfolio";
import Products from "./Products";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <main>
     <Homepage/>
      </main>
    </>
  );
};

export default Home;
